// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiL46NORhakMVBeJ7oh6S88pvGbT6tFO8',
    appId: '1:18544043319:web:1c8f38e95542f43c94a6b2',
    messagingSenderId: '18544043319',
    projectId: 'chatpal-b93a8',
    authDomain: 'chatpal-b93a8.firebaseapp.com',
    storageBucket: 'chatpal-b93a8.firebasestorage.app',
    measurementId: 'G-C942QZNNM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4eYOJnuUBjqDFIX_pSn_4ED0tu_DrFEI',
    appId: '1:18544043319:android:93d1bda8dd6b021594a6b2',
    messagingSenderId: '18544043319',
    projectId: 'chatpal-b93a8',
    storageBucket: 'chatpal-b93a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcTkReduY7uZSkwr40HDVN3s7GDtAR9Dw',
    appId: '1:18544043319:ios:7410c2635679556194a6b2',
    messagingSenderId: '18544043319',
    projectId: 'chatpal-b93a8',
    storageBucket: 'chatpal-b93a8.firebasestorage.app',
    iosBundleId: 'com.kumarvarun3834.chatpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcTkReduY7uZSkwr40HDVN3s7GDtAR9Dw',
    appId: '1:18544043319:ios:7410c2635679556194a6b2',
    messagingSenderId: '18544043319',
    projectId: 'chatpal-b93a8',
    storageBucket: 'chatpal-b93a8.firebasestorage.app',
    iosBundleId: 'com.kumarvarun3834.chatpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiL46NORhakMVBeJ7oh6S88pvGbT6tFO8',
    appId: '1:18544043319:web:8cd48bca1a6ff44894a6b2',
    messagingSenderId: '18544043319',
    projectId: 'chatpal-b93a8',
    authDomain: 'chatpal-b93a8.firebaseapp.com',
    storageBucket: 'chatpal-b93a8.firebasestorage.app',
    measurementId: 'G-179BRS69NQ',
  );
}
